# Generated by Django 5.2.1 on 2025-05-15 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("post", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="attachments",
            field=models.ManyToManyField(blank=True, to="post.postattachment"),
        ),
    ]
