# Generated by Django 5.2.1 on 2025-05-15 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("post", "0002_alter_post_attachments"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="post",
            options={"ordering": ("-created_at",)},
        ),
    ]
